# Working with matrices in Python

Matrices can be described by multidimensional `numpy` arrays, and we can perform matrix multiplication with the `numpy.matmul()` function. [^footnote]

[^footnote]: You can get the same results using `numpy.dot()`, but we encourage `numpy.matmul()` because it makes the final code easier to read and follow.

In [2]:
import numpy as np

r = np.array([3,4])
M = np.array([[0,-1],
              [1, 0]])
r_prime = np.matmul(M, r)
print(r_prime)

[-4  3]


The inverse of a matrix can be calculated (if it exists) using `numpy.linalg.inv()`.

In [3]:
N = np.linalg.inv(M)
print(N)

[[ 0.  1.]
 [-1. -0.]]


In [4]:
np.matmul(N, r_prime) # we should recover our original vector

array([3., 4.])

Matrix&ndash;matrix multiplication can also be performed using `numpy.matmul()`:

In [5]:
MM = np.matmul(M,M) # Two 90 degree rotations should be a 180 degree rotation.
print(MM)

[[-1  0]
 [ 0 -1]]
